# Applying for Higher Education Academy Fellowship in The Univerity of Bath

This page is dedicated to those members of staff in the University of Bath's Maths Department who are planning to apply for the Higher Education Academy Fellowship.  The resources on this page will *only* be accessible to those members of staff and GTAs of the University of Bath.  The HEA Champion for the Maths Department will be me.

### Key Dates 2025-2026

| Review Round | Gateway Deadline | Submission Deadline |
|:------------:|:----------------:|:-------------------:|
| Round 1      | 12/09/2025       | 17/10/2025          |
| Round 2      | 09/01/2026       | 06/02/2026          |
| Round 3      | 10/04/2026       | 15/05/2026          |

### Steps for Application

0. Enrol (as a student) and complete [First Steps into Teaching](https://moodle.bath.ac.uk/enrol/index.php?id=58363).  This step might not be necessary for those with prior teaching experience.

1. Check the appropriate level of application using the [Fellowship Category Tool](https://www.advance-he.ac.uk/form/fellowship-decision-tool-2023).

2. Sign up and the attend the following courses:
     + **Probationers**:  *01 - Introduction to Probation Pathway to Fellowships (Pathways)* on the [CLT website](https://teachinghub.bath.ac.uk/events/categories/pathways/).
     + **Non-Probationers**:  *20 - Introduction to Fellowship (Associate Fellow, Fellow and Senior Fellow)* on the [CLT website](https://teachinghub.bath.ac.uk/events/categories/pathways/).
     * **GTAs**:  *GTA Pathway to Fellowship* on [Moodle](https://moodle.bath.ac.uk/course/view.php?id=59695&section=16).

3. Sign up for and attend *21 - Reflective Writing Support (Associate Fellow, Fellow and Senior Fellow)* through the [CLT website](https://teachinghub.bath.ac.uk/events/categories/pathways/).

4. Make sure you have been enrolled on the correct Moodle resources pages (by contacting [acdev](mailto:acdev@bath.ac.uk) or [me](mailto:waaa21@bath.ac.uk)):
     + [Probationer Pathway](https://moodle.bath.ac.uk/enrol/index.php?id=59363)
     + [Experiential Pathway](https://moodle.bath.ac.uk/course/view.php?id=59370)
     + [GTA Pathway](https://moodle.bath.ac.uk/course/view.php?id=59695&section=16)

5. Make sure you have been enrolled on the [Gateway to Fellowship Submission](https://moodle.bath.ac.uk/course/view.php?id=59371) on Moodle.

6. Inform your department's HEA Champion about your intention to submit before the *Gateway Deadline*.

7. Work with your department's HEA Champion to draft a fellowship application.

8. Identify your advocates
     + **AFHEA**:  1 advocate
     + **FHEA**:  2 advocates for non-probationers; 1 advocate and 1 senior observer for probationers
     + **SFHEA**:  1 internal advocate and 1 external advocate.

9. Write and receive feedback on your application from your department's HEA Champion.

10. Act on the feedback, finalise the application and pass it to advocates to complete their statements.

11. Submit your application before the *Submission Deadline*.