# BSc Final Year Project Proposals

### Random Quadrature

:::{.callout-note title="Details" collapse=true icon=false}

**Pre-Requisite Units:**

- MA22037 Numerical Analysis

**Recommended Pre-Requisite Units:**

- MA22032 Analysis 2A

**Pre-Requisite Knowledge:**  Coding in Python or MATLAB

**Project Description:**

In this project, you will investigate how randomness can be incorporated into quadrature methods.

For example, consider the rectangle rule for quadrature, the points are usually evenly spaced across the domain of integration.  To improve the accuracy, three things can be done: either more points need to be considered, a higher order method is needed (like trapezium or Simpson’s) or the points need to be distributed differently.
Suppose that the points are now randomly distributed across the domain and the rectangle rule is performed.  Would choosing a random set of point with a lower order method across several iterations be better than a higher order method once?  What are the advantages of using the random points over equally spaced points?  Is there a probability distribution that is better than others?

This project will investigate and study different probability distributions and analyse the difference in their performance compared to one another and compared to higher order methods.

This project will require a good base knowledge of numerical computations and coding (in Python or MATLAB) and a good understanding of the convergence of quadrature methods.
:::

<br>

### Collocation Methods

:::{.callout-note title="Details" collapse=true icon=false}

**Pre-Requisite Units:**

- MA22037 Numerical Analysis

**Pre-Requisite Knowledge:**  Coding in MATLAB or Python

**Project Description:**

In this project, you will use different collocation methods to solve some differential and integral equations.

Consider a differential or integral equation that is difficult to solve explicitly.  One way of solving it would be by assuming that the general solution takes the form of an infinite polynomial (a Taylor series), and the coefficients can be found recursively.  What if the solution was assumed to be a linear combination of Legendre polynomials instead, or Chebyshev polynomials, would the series solution converge to the exact solution quicker?  Are there advantages to using one set of orthogonal polynomials compared to others?  Does a set of polynomials have more desirable properties compared to others?

This process will be used to find solutions to differential and integral equations both analytically and will be numerically verified.
:::

<br>

### The Gamma Function

:::{.callout-note title="Details" collapse=true icon=false}

**Pre-Requisite Units:**

- MA22032 Analysis 2A
- MA22323 Analysis 2B

**Pre-Requisite Knowledge:**  Asymptotic Methods

**Project Description:**

In this project, you will investigate the different forms of the Gamma function in mathematical and historical contexts.

The Gamma function has several forms, each with their own unique properties and applications.  The Gamma function can be defined in terms of integrals, Mellin transformation, limits, factorials, double factorials, trigonometric functions, infinite products, asymptotic approximations, complex residues and many other forms.  This project will aim to understand and derive some of these forms and attempt to form a connection between them, factoring in their uses and historical context in the development of the Gamma function.
:::

<br>

### Fluid Dynamics & Generation of Lift

:::{.callout-note title="Details" collapse=true icon=false}

**Pre-Requisite Units:**

- MA22016 Differential Equations & Vector Calculus
- MA22021 Partial Differential Equations
- MA32051 Fluid Dynamics

**Project Description:**

In this project, you will introduce the basic principles of fluid dynamics and flow profiles, deriving them from the momentum equations and reproducing the Navier-Stokes equations.

This project will attempt to derive the Navier-Stokes equations from the governing equations of fluid flow.  This will then be restricted into specific profiles, such as the Poiseuille or Blasius boundary layer flows in different domains.  Bernoulli’s pressure equations will be derived to establish pressure differences in flow profiles and that will lead to flow domain that could generate lift.
:::

<br>

### Theory of Contunued Fractions

:::{.callout-note title="Details" collapse=true icon=false}

**Pre-Requisite Units:**

- MA32064 Number Theory & Cryptography

**Recommended Pre-Requisite Units:**

- MA22020 Advanced Linear Algebra

**Project Description:**

In this project, you will establish the theory of continued fractions and investigate their properties.

This will project cover the general theory of continued fractions, investigate the convergence properties, how to generate the fractions themselves and demonstrate some examples, both in typical and atypical form.  For example, the irrational number $\pi$ can be written in many different continued fraction forms:
$$\pi=3+\frac{1}{7+\frac{1}{15+\frac{1}{292+\frac{1}{1+\frac{1}{1+\frac{1}{1+\frac{1}{2+...}}}}}}}, \quad \pi=3+\frac{1^2}{6+\frac{3^2}{6+\frac{5^2}{6+\frac{7^2}{6+\frac{9^2}{6+\frac{11^2}{6+...}}}}}}, \quad \pi=\frac{4}{1+\frac{1^2}{3+\frac{2^2}{5+\frac{3^3}{7+\frac{4^2}{9+\frac{4^2}{11+...}}}}}}, \quad \pi=\frac{4}{1+\frac{1^2}{2+\frac{3^2}{2+\frac{5^2}{2+\frac{7^2}{2+\frac{9^2}{2+}}}}}}$$
These different forms will be investigated, their convergence studied and the different ways in which these can be derived.
:::

<br>

### Statistical Mechanics

:::{.callout-note title="Details" collapse=true icon=false}

**Pre-Requisite Units:**

- MA22016 Differential Equations & Vector Calculus
- MA22021 Partial Differential Equations

**Pre-Requisite Knowledge:**  Vectors, Vector Calculus, Newtonian Mechanics

**Project Description:**

In this project, you will investigate the principles of statistical mechanics and their applications.

You will start from Newtonian mechanics of a single particle and building to a Hamiltonian formulation.  The project will investigate the principles of statistical mechanics in the ensemble statistics and applications in physics, such as the ideal gas law.
:::

<br>

### Integral Transforms & Their Applications

:::{.callout-note title="Details" collapse=true icon=false}

**Pre-Requisite Units:**

- MA22016 Differential Equations & Vector Calculus

**Recommended Pre-Requisite Units:**

- MA32046 Control Theory

**Co-Requisite Units:**

- MA32062 Methods for Differential Equations

**Project Description:**

This project will investigate different integral transforms and theory applications.
There are many differential and integral equations that cannot be solved using conventional means, or if they can be, the process can be tedious.  In this case, integral transformations can be used as a workaround, converting the equation into a different, more easily solvable form, before solving and reversing the transformation.  This project will investigate different possible integrals transforms (such as one-sided and two-sided Laplace, Fourier, Mellin, Weierstrass and others), their properties will be studied and proven and their different uses and applications will be investigated.
:::