# Student Projects

I am open to accepting Y3 students willing to do a [Final Year BSc Project](https://www.bath.ac.uk/catalogues/2026-2027/ma/MA32050.html) on the [following topics](Project_Desc.qmd), other topics are also up for discussion.

I am also open to accepting [MMath](https://www.bath.ac.uk/catalogues/2026-2027/ma/MA52027.html) projects with a topic up for discussion.

## BSc Projects

* Modelling Blood Flow in the Circulatory System, [**Fylvia Iyeli**](https://www.linkedin.com/in/fylvia/), *2026*

* Integral Transforms & Their Applications, [**Jasmine Patra**](https://www.linkedin.com/in/jasminekpatra/), *2026*

* Constructing a Structural Model of Algebra Task Difficulty With Implications for Design of Digital Teaching, **Joseph Taylor**, *2026*

* The Lorenz System and Applications of Chaos, [**Samuel Hancock**](https://www.linkedin.com/in/samuel-hancock-894a87298/), *2024*

* Approximate Methods for Solving Ordinary Differential Equations, **Andrea Zhang**, *2023*

* A Brief Overview of Special Functions and Their Applications, **Emilia Lewis**, *2022*

## MMath Projects

* Mathematical Modelling of Issues in the Department for Education, [**Addie Baker**](https://samba.ac.uk/student/addie-baker/), *2025*