# Talks & Seminars

## Mathematics Education & Outreach

- Coding in Maple (*Bath Student Symposia, UoB*)
- Teaching Mathematical Foundations in Y1 (*BAMC 2026, UEA*)
- Interactivity in the Classroom (*PoLIS, UoB*)
- How to Give a Public Talk (*Bath PGR Symposium, UoB*)
- Outreach Outside of Higher Education (*SAMBa Conference, UoB*)
- HEA Fellowship in Maths ([*PRiME Seminar Series*](https://prime-bath.github.io/PRiME/seminars.html#HEA-Fellowship-in-Maths)*, UoB*)

## Pop Culture & General Interest

- Why Superpowers are Impossible (*Cardiff PGR Seminars*; *UoB Maths Society*; *Student Minds Charity Seminar*)
- Will we Survive the Zombie Apocalypse? (*Cardiff PGR Seminar*; *Bath PGR Seminar*)
- The Science of Star Wars (*Cardiff PGR Seminar*; *Techniquest Star Wars Day*; *Cardiff Science Café*)
- Is Maths Invented or Discovered? (*UoB Philosophy Society*)
- The Earth is NOT Flat:  Proof by Pizza (*Cardiff Science Café*)
- What is the Biggest Number? (*Cardiff PGR Seminar*)
- How Likely are you to Get Sick? (*Cardiff PGR Seminar*)
- Quantification of Pizza Baking Properties of Different Cheeses and their Correlation with Cheese Functionality (*Cardiff PGR Seminar*)

## Fluid Dyanmics & Hyrdodynamic Stability

- Gregynog Mathematics Colloquium (*Gregynog Hall, Wales*)
- $11^{\mathrm{th}}$ European Fluid Mechanics Conference (*Seville, Spain*)
- $50^{\mathrm{th}}$ British Applied Mathematics Colloquium (*Cambridge, UK*)
- Cardiff Applied Maths Seminars (*Cardiff, Wales*)